docs: document LANCE_BYPASS_SPILLING environment variable
lancedb/lance pull request #2276
Opened 2024-04-30 22:48 UTC by alexkohler

2024-04-30 22:49 UTC, alexkohler commented
Discord thread with more context: https://discord.com/channels/1030247538198061086/1232077501719642112

2024-04-30 22:57 UTC, westonpace requested changes
One minor suggestion

2024-04-30 22:57 UTC, westonpace commented on python/python/lance/dataset.py
> +        Note that the ``LANCE_BYPASS_SPILLINGa environment variable can be used to
```suggestion
        Note that the ``LANCE_BYPASS_SPILLING`` environment variable can be used to
```

2024-04-30 23:09 UTC, alexkohler commented
whoops - fixed!

2024-05-01 04:28 UTC, westonpace approved these changes
Thanks for your help!

2024-05-01 04:28 UTC, merged