feat!: simplify take row api
lancedb/lance pull request #2664
Opened 2024-07-30 20:07 UTC by eddyxu

Change `take_rows` and `take` APIs to allow directly take `Schema` again.

2024-07-30 20:33 UTC, eddyxu commented
Windows failure is not relevant

2024-07-31 15:29 UTC, wjones127 requested changes

2024-07-31 16:05 UTC, eddyxu commented on rust/lance/src/dataset.rs
> +}
Fixed.

2024-07-31 16:14 UTC, westonpace approved these changes

2024-07-31 16:34 UTC, wjones127 approved these changes

2024-07-31 16:35 UTC, wjones127 commented
Thanks for doing this. I like this interface a lot better.

2024-07-31 17:33 UTC, merged