feat: implement DataBlockBuilderImpl for variable width data block
lancedb/lance pull request #3096
Opened 2024-11-05 22:23 UTC by broccoliSpicy

This PR implements `DataBlockBuilderImpl` trait for Variable Width Data, so we can enable read Variable Width data in Lance 2.1

2024-11-05 22:46 UTC, westonpace requested changes
Can you add some test cases?  Even just a basic simple case would be good.

2024-11-05 22:46 UTC, westonpace commented on rust/lance-encoding/src/data.rs
> +    as_type_mut_ref!(as_dictionary_mut_ref, Dictionary, DictionaryDataBlock);
Can we call the function / macro name `..._mut` and not `..._mut_ref` for consistency with things like `[Option](https://doc.rust-lang.org/std/option/enum.Option.html#method.as_mut)`

2024-11-05 22:46 UTC, westonpace commented on rust/lance-encoding/src/data.rs
> +        self.offsets.push(self.bytes.len() as u32);
I'm not sure this is correct.  Shouldn't you be extending from `block.offsets` and not pushing a single value?

2024-11-05 22:46 UTC, westonpace commented on rust/lance-encoding/src/data.rs
> +pub struct VariableWidthDataBlockBuilder1 {
```suggestion
pub struct VariableWidthDataBlockBuilder {
```

2024-11-06 21:24 UTC, broccoliSpicy commented
thanks for the review, I merged the code in this PR in PR #3099 and will close this one.

2024-11-06 21:24 UTC, closed without merging